server:
  port: 8999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userdetails
          uri: lb://userdetails
          predicates:
            - Path=/user/**
        - id: contact
          uri: lb://contact
          predicates:
            - Path=/contact/**
